#! /bin/bash -

# ENVIRONMENT VARIABLES
 
JDK_PATH=/usr/lib/jvm/java-8-openjdk-amd64
WEKA=/usr/PycharmProjects/DeepWalk_plus/mairesse/PersonalityRecognizer/lib/weka.jar

# ----------------------------------

COMMONS_CLI=./lib/commons-cli-1.0.jar
MRC=./lib/jmrc.jar

LIBS=.:$WEKA:$COMMONS_CLI:$MRC:bin/

$JDK_PATH/bin/java -Xmx512m -classpath $LIBS recognizer.PersonalityRecognizer $*



