.\" dummy line
.TH PsychDict 1 "27 April 1987"
.UC 4
.SH NAME
PsychDict \- reduce MRC Psycholinguistic Database 
.SH SYNOPSIS
.B PsychDict 
.SH DESCRIPTION

The full MRC Psycholinguistic Database dictionary of 150837 entries occupies 11MByte of disc space. This may
be more than many potential users are willing to spare. The program PsychDict
reduces the dictionary to containing only entries for words about which there is
psychological information available. That is, which have entries for any of 
the frequency counts, FAM, CONC, IMAG, MEANC, MEANP or AOA. This reduced dictionary
will contain most of the information required for the preperation of 
psycholinguistic stimuli, although it will not offer a complete word list or
syntactic core. Similar samples for these items can be produced by using 
.I dict
with the 
.I -entry 
option.

The program directs output to the standard output, and will produce a file of
about 3MByte containing entries for 39300 words. An example command line would be:

.I
PsychDict > filename

.SH OPTIONS
.I none
.fi
.SH "SEE ALSO"
M. Coltheart (1981)
The MRC Psycholinguistic Database
.B
Quarterly Journal of Experimental Psychology, 33A, 
497-505 
.PP
M. Wilson (1987)
MRC Psycholinguistic Database: Machine Usable Dictionary, Version 2.
Memo - IKBS Section, Rutherford Appleton Lab.
.SH AUTHORS
.nf
		Michael Wilson
		Rutherford Appleton Laboratory,
		Oxon, U.K.
.fi
